name: CI

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: '15 14 * * 1'
  workflow_dispatch:

jobs:
  build-test:
    name: Test on ${{ matrix.os }} / Python ${{ matrix.python-version }} / NumPy ${{ matrix.numpy-version || 'default' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.12"
            numpy-version: "<2"
          - os: ubuntu-latest
            python-version: "3.12"
            numpy-version: ">=2"
          - os: ubuntu-latest
            python-version: "3.11"
            numpy-version: ""
          - os: macos-latest
            python-version: "3.11"
            numpy-version: ""
          - os: macos-latest
            python-version: "3.12"
            numpy-version: ""

    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Upgrade pip and install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel build

      - name: Install package with test dependencies
        run: |
          pip install --force-reinstall "numpy${{ matrix.numpy-version }}"
          pip install -e .[test]

      - name: Print installed packages
        run: |
          pip list --format=columns

      - name: Run tests
        run: |
          pytest
